name: Quality Assurance

on:
  push

jobs:
  quality-assurance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_AT }}

      - name: Setup NodeJS 15
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: |
          npm run fetch
          npm run parse
          npm run build:globals
        env:
          FIGMA_FILE_TOKEN: ${{ secrets.FIGMA_FILE_TOKEN }}
          FIGMA_AUTH_TOKEN: ${{ secrets.FIGMA_AUTH_TOKEN }}

      - name: Test
        run: npm test
