name: Release Vivid

on:
  push:
    tags:
      - v*

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_AT }}

      - name: Publish design tokens
        run: echo here
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}