name: Release Vivid

on:
  push:
    tags:
      - v*

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract release version
          id: extractVersion
          run: echo "::set-output name=version::$(echo ${GITHUB_REF##*/v})"

      - name: Publish design tokens
        run: echo ${{ steps.extractVersion.outputs.version }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}