name: Release Design Token Properties

on:
  push:
    tags:
      - v*

jobs:
  release-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Setup NodeJS 15
        uses: actions/setup-node@v1
        with:
          node-version: 15
          registry-url: 'https://npm.pkg.github.com'

      - name: Update tokens data & bump package version to ${{ steps.extractVersion.outputs.version }}
        run: |
          npm install
          npm run fetch
          npm run parse
          npm run build:globals
          npm run bump ${{ steps.extractVersion.outputs.version }}

      - name: Publish design tokens
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
